// <auto-generated />
using System;
using Infrastructure.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MainDataContext))]
    partial class MainDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.BaseGravable.BaseGravableVehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<int>("Cilindraje")
                        .HasColumnType("integer");

                    b.Property<string>("ClaseVehiculo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Linea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Pasajeros")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BaseGravableVehiculos");
                });

            modelBuilder.Entity("Domain.Models.BaseGravable.BaseGravableVigencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioVigencia")
                        .HasColumnType("integer");

                    b.Property<int>("BaseGravableVehiculoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorComercial")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BaseGravableVehiculoId");

                    b.ToTable("BaseGravableVigencia");
                });

            modelBuilder.Entity("Domain.Models.Cartera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("EstaEnProcesoCoactivo")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPagado")
                        .HasColumnType("boolean");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<int?>("ReciboId")
                        .HasColumnType("integer");

                    b.Property<bool>("TieneInteres")
                        .HasColumnType("boolean");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorInteres")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("integer");

                    b.Property<int>("Vigencia")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReciboId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Cartera");
                });

            modelBuilder.Entity("Domain.Models.Descuento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Desde")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Hasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Descuentos");
                });

            modelBuilder.Entity("Domain.Models.Interes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Desde")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Hasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("Intereses");
                });

            modelBuilder.Entity("Domain.Models.Parametro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BancoTercero")
                        .HasColumnType("text");

                    b.Property<string>("BancoTransito")
                        .HasColumnType("text");

                    b.Property<string>("CargoSecretario")
                        .HasColumnType("text");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text");

                    b.Property<bool>("CobraAdicional")
                        .HasColumnType("boolean");

                    b.Property<string>("Correo")
                        .HasColumnType("text");

                    b.Property<string>("CuentaTercero")
                        .HasColumnType("text");

                    b.Property<string>("CuentaTransito")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaLimiteSancion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MetodoImpuesto")
                        .HasColumnType("integer");

                    b.Property<string>("Nit")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreSecretario")
                        .HasColumnType("text");

                    b.Property<decimal>("PorcentajeSancion")
                        .HasColumnType("numeric");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<decimal>("ValorCostasCoactivo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorCostasPersuasivo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorRecibo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorSistema")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Parametros");
                });

            modelBuilder.Entity("Domain.Models.ProcesoLiquidacion.Liquidacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaLiquidacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProcesoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalDeuda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UltimoPagoVigencia")
                        .HasColumnType("integer");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("integer");

                    b.Property<int>("VigenciaDesde")
                        .HasColumnType("integer");

                    b.Property<int>("VigenciaHasta")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcesoId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Liquidacion");
                });

            modelBuilder.Entity("Domain.Models.ProcesoLiquidacion.LiquidacionDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarteraId")
                        .HasColumnType("integer");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LiquidacionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorInteres")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Vigencia")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarteraId");

                    b.HasIndex("LiquidacionId");

                    b.ToTable("LiquidacionDetalle");
                });

            modelBuilder.Entity("Domain.Models.ProcesoLiquidacion.Proceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Desde")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoProceso")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaMandamiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaProceso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Hasta")
                        .HasColumnType("integer");

                    b.Property<int?>("NumeroProceso")
                        .HasColumnType("integer");

                    b.Property<string>("Resolucion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ResolucionSancion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TipoProceso")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Procesos");
                });

            modelBuilder.Entity("Domain.Models.Recibo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Desde")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<decimal>("Estampillas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaAplica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaProceso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Hasta")
                        .HasColumnType("integer");

                    b.Property<decimal>("InteresMora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorCargaDatos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorRodamiento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotalSistema")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Recibos");
                });

            modelBuilder.Entity("Domain.Models.Tarifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioFiscal")
                        .HasColumnType("integer");

                    b.Property<int>("ConceptoTarifa")
                        .HasColumnType("integer");

                    b.Property<int>("RangoFinal")
                        .HasColumnType("integer");

                    b.Property<int>("RangoInicial")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoServicio")
                        .HasColumnType("integer");

                    b.Property<int>("TipoServicioVehiculo")
                        .HasColumnType("integer");

                    b.Property<int>("TipoVehiculoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TipoVehiculoId");

                    b.ToTable("Tarifas");
                });

            modelBuilder.Entity("Domain.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<bool>("IsHabilitado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UsuarioCreo")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_creo");

                    b.Property<int?>("UsuarioModifico")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_modifico");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Domain.Models.Uvt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("indesde");

                    b.Property<DateTime>("FechaHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inhasta");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.ToTable("Uvts");
                });

            modelBuilder.Entity("Domain.Models.Vehiculos.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Codigo")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Colores");
                });

            modelBuilder.Entity("Domain.Models.Vehiculos.HistorialPropietario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PropietarioId")
                        .HasColumnType("integer");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PropietarioId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("HistorialPropietarios");
                });

            modelBuilder.Entity("Domain.Models.Vehiculos.Linea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdMarca")
                        .HasColumnType("integer");

                    b.Property<int>("MarcaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.ToTable("Lineas");
                });

            modelBuilder.Entity("Domain.Models.Vehiculos.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("Domain.Models.Vehiculos.Propietario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Propietarios");
                });

            modelBuilder.Entity("Domain.Models.Vehiculos.TipoVehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Codigo")
                        .HasColumnType("integer");

                    b.Property<int>("ModalidadServicio")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<decimal?>("Uvt")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("TipoVehiculos");
                });

            modelBuilder.Entity("Domain.Models.Vehiculos.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacidadCarga")
                        .HasColumnType("integer");

                    b.Property<int>("Cilindraje")
                        .HasColumnType("integer");

                    b.Property<int>("ColorId")
                        .HasColumnType("integer");

                    b.Property<string>("DocumentoPropietario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstadoProceso")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoProcesoId")
                        .HasColumnType("integer");

                    b.Property<int>("LineaId")
                        .HasColumnType("integer");

                    b.Property<int>("MarcaId")
                        .HasColumnType("integer");

                    b.Property<int>("Modelo")
                        .HasColumnType("integer");

                    b.Property<int>("PagoHasta")
                        .HasColumnType("integer");

                    b.Property<int>("Pasajeros")
                        .HasColumnType("integer");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<int>("PropietarioId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoCarroceriaId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoIdentificacionId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoServicioVehiculo")
                        .HasColumnType("integer");

                    b.Property<int>("TipoVehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("LineaId");

                    b.HasIndex("MarcaId");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.HasIndex("PropietarioId");

                    b.HasIndex("TipoVehiculoId");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("Domain.Models.BaseGravable.BaseGravableVigencia", b =>
                {
                    b.HasOne("Domain.Models.BaseGravable.BaseGravableVehiculo", "BaseGravableVehiculo")
                        .WithMany("Vigencias")
                        .HasForeignKey("BaseGravableVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseGravableVehiculo");
                });

            modelBuilder.Entity("Domain.Models.Cartera", b =>
                {
                    b.HasOne("Domain.Models.Recibo", "Recibo")
                        .WithMany()
                        .HasForeignKey("ReciboId");

                    b.HasOne("Domain.Models.Vehiculos.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recibo");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Domain.Models.ProcesoLiquidacion.Liquidacion", b =>
                {
                    b.HasOne("Domain.Models.ProcesoLiquidacion.Proceso", "Proceso")
                        .WithMany("Liquidaciones")
                        .HasForeignKey("ProcesoId");

                    b.HasOne("Domain.Models.Vehiculos.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proceso");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Domain.Models.ProcesoLiquidacion.LiquidacionDetalle", b =>
                {
                    b.HasOne("Domain.Models.Cartera", "Cartera")
                        .WithMany()
                        .HasForeignKey("CarteraId");

                    b.HasOne("Domain.Models.ProcesoLiquidacion.Liquidacion", "Liquidacion")
                        .WithMany("Detalles")
                        .HasForeignKey("LiquidacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cartera");

                    b.Navigation("Liquidacion");
                });

            modelBuilder.Entity("Domain.Models.ProcesoLiquidacion.Proceso", b =>
                {
                    b.HasOne("Domain.Models.Vehiculos.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Domain.Models.Recibo", b =>
                {
                    b.HasOne("Domain.Models.Vehiculos.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Domain.Models.Tarifa", b =>
                {
                    b.HasOne("Domain.Models.Vehiculos.TipoVehiculo", "TipoVehiculo")
                        .WithMany()
                        .HasForeignKey("TipoVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoVehiculo");
                });

            modelBuilder.Entity("Domain.Models.Vehiculos.HistorialPropietario", b =>
                {
                    b.HasOne("Domain.Models.Vehiculos.Propietario", "Propietario")
                        .WithMany()
                        .HasForeignKey("PropietarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Vehiculos.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propietario");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Domain.Models.Vehiculos.Linea", b =>
                {
                    b.HasOne("Domain.Models.Vehiculos.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("Domain.Models.Vehiculos.Vehiculo", b =>
                {
                    b.HasOne("Domain.Models.Vehiculos.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Vehiculos.Linea", "Linea")
                        .WithMany()
                        .HasForeignKey("LineaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Vehiculos.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Vehiculos.Propietario", "Propietario")
                        .WithMany("Vehiculos")
                        .HasForeignKey("PropietarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Vehiculos.TipoVehiculo", "TipoVehiculo")
                        .WithMany()
                        .HasForeignKey("TipoVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Linea");

                    b.Navigation("Marca");

                    b.Navigation("Propietario");

                    b.Navigation("TipoVehiculo");
                });

            modelBuilder.Entity("Domain.Models.BaseGravable.BaseGravableVehiculo", b =>
                {
                    b.Navigation("Vigencias");
                });

            modelBuilder.Entity("Domain.Models.ProcesoLiquidacion.Liquidacion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Domain.Models.ProcesoLiquidacion.Proceso", b =>
                {
                    b.Navigation("Liquidaciones");
                });

            modelBuilder.Entity("Domain.Models.Vehiculos.Propietario", b =>
                {
                    b.Navigation("Vehiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
